import { PrismaClient } from "@prisma/client";
import { dispatchIngestWorkflow, githubDispatchConfig } from "./github";
import type { AdminActor, AdminRepository, AgentRun, AuditLog, Channel, ContentItem, SearchSettings, Topic } from "./types";

type Db = PrismaClient;
const json = (value: unknown) => value == null ? undefined : JSON.parse(JSON.stringify(value));

export class PrismaAdminRepository implements AdminRepository {
  constructor(private readonly db: Db = new PrismaClient()) {}
  private audit(actor: AdminActor, action: string, entityType: string, entityId: string | null, before: unknown, after: unknown) { return this.db.auditLog.create({ data: { adminId: actor.id, action, entityType, entityId, beforeJson: json(before), afterJson: json(after) } }); }
  private mapTopic(row: any): Topic { return { id: row.id, slug: row.slug, nameZhHant: row.nameZhHant, description: row.description, parentTopicId: row.parentTopicId, isActive: row.isActive, sortOrder: row.sortOrder, keywords: (row.keywords ?? []).map((k: any) => ({ id: k.id, keyword: k.keyword, keywordType: k.keywordType, weight: Number(k.weight), isActive: k.isActive })) }; }
  async listTopics() { return (await this.db.topic.findMany({ include: { keywords: true }, orderBy: [{ sortOrder: "asc" }, { nameZhHant: "asc" }] })).map((row: any) => this.mapTopic(row)); }
  async createTopic(input: Omit<Topic, "id">, actor: AdminActor) { const row = await this.db.topic.create({ data: { slug: input.slug, nameZhHant: input.nameZhHant, description: input.description, parentTopicId: input.parentTopicId, isActive: input.isActive, sortOrder: input.sortOrder, keywords: { create: input.keywords.map(({ id: _id, ...k }) => ({ ...k, keywordType: k.keywordType })) }, searchSettings: { create: {} } }, include: { keywords: true } }); const topic = this.mapTopic(row); await this.audit(actor, "create", "topic", topic.id, null, topic); return topic; }
  async updateTopic(id: string, input: Partial<Omit<Topic, "id">>, actor: AdminActor) { const existing = await this.db.topic.findUnique({ where: { id }, include: { keywords: true } }); if (!existing) return null; const before = this.mapTopic(existing); const row = await this.db.topic.update({ where: { id }, data: { slug: input.slug, nameZhHant: input.nameZhHant, description: input.description, parentTopicId: input.parentTopicId, isActive: input.isActive, sortOrder: input.sortOrder, ...(input.keywords ? { keywords: { deleteMany: {}, create: input.keywords.map(({ id: _id, ...k }) => k) } } : {}) }, include: { keywords: true } }); const topic = this.mapTopic(row); await this.audit(actor, "update", "topic", id, before, topic); return topic; }
  async disableTopic(id: string, actor: AdminActor) { return this.updateTopic(id, { isActive: false }, actor); }
  private mapSettings(row: any): SearchSettings { return { topicId: row.topicId, freshnessDays: row.freshnessDays, candidateLimit: row.candidateLimit, topN: row.topN, minDurationSeconds: row.minDurationSeconds, maxDurationSeconds: row.maxDurationSeconds, excludeShorts: row.excludeShorts, minViewCount: Number(row.minViewCount), minEngagementScore: Number(row.minEngagementScore), growthGuardrailEnabled: row.growthGuardrailEnabled, minViewsPerDay: row.minViewsPerDay, autoPublish: row.autoPublish, youtubeRegionCode: row.youtubeRegionCode, relevanceLanguage: row.relevanceLanguage, searchOrder: row.searchOrder, scheduleCron: row.scheduleCron }; }
  async getSettings(topicId?: string) { return (await this.db.topicSearchSetting.findMany({ where: topicId ? { topicId } : undefined })).map((row: any) => this.mapSettings(row)); }
  async updateSettings(input: SearchSettings, actor: AdminActor) { const beforeRow = await this.db.topicSearchSetting.findUnique({ where: { topicId: input.topicId } }); const data = { ...input, minViewCount: BigInt(input.minViewCount) }; const row = await this.db.topicSearchSetting.upsert({ where: { topicId: input.topicId }, create: data, update: data }); const result = this.mapSettings(row); await this.audit(actor, "update", "topic_search_settings", input.topicId, beforeRow ? this.mapSettings(beforeRow) : null, result); return result; }
  private mapChannel(row: any): Channel { return { id: row.id, sourceChannelId: row.sourceChannelId, handle: row.handle, title: row.title, listType: row.listType, trustWeight: Number(row.trustWeight), recommendationReason: row.recommendationReason, isActive: row.listType !== "neutral" }; }
  async listChannels() { return (await this.db.channel.findMany({ where: { listType: { not: "neutral" } }, orderBy: { updatedAt: "desc" } })).map((row: any) => this.mapChannel(row)); }
  async upsertChannel(input: Omit<Channel, "id" | "isActive">, actor: AdminActor) { const key = { sourceType_sourceChannelId: { sourceType: "youtube" as const, sourceChannelId: input.sourceChannelId } }; const before = await this.db.channel.findUnique({ where: key }); const row = await this.db.channel.upsert({ where: key, create: { sourceType: "youtube", ...input }, update: input }); const result = this.mapChannel(row); await this.audit(actor, before ? "update" : "create", "channel", row.id, before ? this.mapChannel(before) : null, result); return result; }
  async disableChannel(id: string, actor: AdminActor) { const before = await this.db.channel.findUnique({ where: { id } }); if (!before) return null; const row = await this.db.channel.update({ where: { id }, data: { listType: "neutral", trustWeight: 0, recommendationReason: null } }); const result = this.mapChannel(row); await this.audit(actor, "disable", "channel", id, this.mapChannel(before), result); return result; }
  private mapContent(row: any): ContentItem { const overrides = (row.rawMetadataJson && typeof row.rawMetadataJson === "object" ? row.rawMetadataJson : {}) as Record<string, unknown>; return { id: row.id, sourceContentId: row.sourceContentId, sourceUrl: row.sourceUrl, title: row.title, channelTitle: row.channelTitle, shortSummary: String(overrides.shortSummary ?? row.summaries?.[0]?.shortSummary ?? ""), difficulty: row.difficulty, tags: Array.isArray(overrides.tags) ? overrides.tags.map(String) : (row.tags ?? []).map((item: any) => item.tag.name), status: row.status, hiddenReason: row.hiddenReason, isPinned: row.isPinned, topicId: row.topics?.[0]?.topicId ?? null, createdAt: row.createdAt.toISOString() }; }
  private contentInclude = { summaries: { orderBy: { createdAt: "desc" as const }, take: 1 }, tags: { include: { tag: true } }, topics: { take: 1 } };
  async listContent(query = "") { const rows = await this.db.contentItem.findMany({ where: { status: { not: "deleted" }, ...(query ? { OR: [{ title: { contains: query, mode: "insensitive" } }, { channelTitle: { contains: query, mode: "insensitive" } }] } : {}) }, include: this.contentInclude, orderBy: { createdAt: "desc" }, take: 500 }); return rows.map((row: any) => this.mapContent(row)); }
  async createContent(input: Omit<ContentItem, "id" | "createdAt">, actor: AdminActor) { const row = await this.db.contentItem.create({ data: { sourceType: "youtube", sourceContentId: input.sourceContentId, sourceUrl: input.sourceUrl, title: input.title, channelTitle: input.channelTitle, status: input.status, difficulty: input.difficulty, hiddenReason: input.hiddenReason, isPinned: input.isPinned, rawMetadataJson: json({ shortSummary: input.shortSummary, tags: input.tags }), ...(input.topicId ? { topics: { create: { topicId: input.topicId, source: "admin" } } } : {}) }, include: this.contentInclude }); const result = this.mapContent(row); await this.audit(actor, "create", "content", row.id, null, result); return result; }
  async updateContent(id: string, input: Partial<Omit<ContentItem, "id" | "createdAt" | "sourceContentId" | "sourceUrl">>, actor: AdminActor) { const existing = await this.db.contentItem.findUnique({ where: { id }, include: this.contentInclude }); if (!existing) return null; const before = this.mapContent(existing); const overrides = { ...(existing.rawMetadataJson as object ?? {}), ...(input.shortSummary !== undefined ? { shortSummary: input.shortSummary } : {}), ...(input.tags !== undefined ? { tags: input.tags } : {}) }; const row = await this.db.contentItem.update({ where: { id }, data: { title: input.title, channelTitle: input.channelTitle, difficulty: input.difficulty, status: input.status, hiddenReason: input.hiddenReason, isPinned: input.isPinned, rawMetadataJson: json(overrides), ...(input.difficulty ? { difficultyOverriddenById: actor.id, difficultyOverriddenAt: new Date() } : {}), ...(input.topicId !== undefined ? { topics: { deleteMany: {}, ...(input.topicId ? { create: { topicId: input.topicId, source: "admin" } } : {}) } } : {}) }, include: this.contentInclude }); const result = this.mapContent(row); await this.audit(actor, "update", "content", id, before, result); return result; }
  async deleteContent(id: string, actor: AdminActor) { return this.updateContent(id, { status: "deleted", hiddenReason: "管理者刪除" }, actor); }
  async contentStatusCounts() { const rows = await this.db.contentItem.groupBy({ by: ["status"], where: { status: { not: "deleted" } }, _count: { _all: true } }); return Object.fromEntries(rows.map((row: any) => [row.status, row._count._all])) as Record<string, number>; }
  private mapRun(row: any): AgentRun { const summary = row.summaryJson && typeof row.summaryJson === "object" ? row.summaryJson : {}; return { id: row.id, status: row.status === "running" ? "running" : row.status, trigger: ["manual", "backfill", "test"].includes(row.triggerType) ? row.triggerType : "scheduled", startedAt: row.startedAt.toISOString(), finishedAt: row.endedAt?.toISOString() ?? null, statistics: Object.fromEntries(Object.entries(summary).filter(([, v]) => typeof v === "number")) as Record<string, number>, events: (row.events ?? []).map((e: any) => ({ id: e.id, phase: e.phase, level: e.level, message: e.message, createdAt: e.createdAt.toISOString() })) }; }
  async listRuns() { return (await this.db.agentRun.findMany({ include: { events: { orderBy: { createdAt: "desc" } } }, orderBy: { startedAt: "desc" }, take: 100 })).map((row: any) => this.mapRun(row)); }
  async getRun(id: string) { const row = await this.db.agentRun.findUnique({ where: { id }, include: { events: { orderBy: { createdAt: "asc" } } } }); return row ? this.mapRun(row) : null; }
  async triggerRun(actor: AdminActor) { const dispatchConfig = githubDispatchConfig(); if (!dispatchConfig) throw new Error("WORKFLOW_DISPATCH_NOT_CONFIGURED"); const recent = await this.db.agentRun.findFirst({ where: { triggerType: "manual", requestedByAdminId: actor.id, startedAt: { gte: new Date(Date.now() - 60_000) } }, select: { id: true } }); if (recent) throw new Error("RATE_LIMITED"); const row = await this.db.agentRun.create({ data: { triggerType: "manual", status: "queued", requestedByAdminId: actor.id }, include: { events: true } }); try { await dispatchIngestWorkflow({ run_id: row.id }, dispatchConfig); } catch (error) { await this.db.agentRun.update({ where: { id: row.id }, data: { status: "failed", endedAt: new Date(), errorMessage: error instanceof Error ? error.message : String(error) } }); throw error; } const result = this.mapRun(row); await this.audit(actor, "trigger", "agent_run", row.id, null, result); return result; }
  async listAuditLogs(): Promise<AuditLog[]> { return (await this.db.auditLog.findMany({ orderBy: { createdAt: "desc" }, take: 500 })).map((row: any) => ({ id: row.id, adminId: row.adminId ?? "system", action: row.action, entityType: row.entityType, entityId: row.entityId, before: row.beforeJson, after: row.afterJson, createdAt: row.createdAt.toISOString() })); }
}
