import { z } from "zod";

const keyword = z.object({ id: z.string().uuid().optional(), keyword: z.string().trim().min(1).max(200), keywordType: z.enum(["positive", "negative", "synonym", "tw_term", "cn_term", "english"]), weight: z.number().min(-100).max(100).default(1), isActive: z.boolean().default(true) });
export const topicCreateSchema = z.object({ slug: z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(100), nameZhHant: z.string().trim().min(1).max(200), description: z.string().trim().max(2000).nullable().default(null), parentTopicId: z.string().uuid().nullable().default(null), isActive: z.boolean().default(true), sortOrder: z.number().int().min(0).max(10000).default(0), keywords: z.array(keyword).max(100).default([]) });
export const topicUpdateSchema = topicCreateSchema.partial().refine((value) => Object.keys(value).length > 0, "至少需要一個欄位");
export const settingsSchema = z.object({ topicId: z.string().uuid(), freshnessDays: z.number().int().min(1).max(3650), candidateLimit: z.number().int().min(1).max(500), topN: z.number().int().min(1).max(100), minDurationSeconds: z.number().int().min(0).max(86400), maxDurationSeconds: z.number().int().min(1).max(86400), excludeShorts: z.boolean(), minViewCount: z.number().int().min(0).max(Number.MAX_SAFE_INTEGER), minEngagementScore: z.number().min(0).max(1), growthGuardrailEnabled: z.boolean(), minViewsPerDay: z.number().int().min(0).max(10_000_000), autoPublish: z.boolean(), youtubeRegionCode: z.string().trim().length(2).transform(v => v.toUpperCase()), relevanceLanguage: z.string().trim().min(2).max(35), searchOrder: z.enum(["relevance", "date", "viewCount"]), scheduleCron: z.string().trim().min(9).max(100) }).superRefine((v, ctx) => { if (v.topN > v.candidateLimit) ctx.addIssue({ code: "custom", path: ["topN"], message: "Top N 不可超過候選數" }); if (v.minDurationSeconds > v.maxDurationSeconds) ctx.addIssue({ code: "custom", path: ["maxDurationSeconds"], message: "最長片長不可小於最短片長" }); });
export const channelSchema = z.object({ sourceChannelId: z.string().trim().min(1).max(200), handle: z.string().trim().max(200).nullable().default(null), title: z.string().trim().min(1).max(300), listType: z.enum(["recommended", "blacklisted"]), trustWeight: z.number().min(-10).max(10).default(0), recommendationReason: z.string().trim().max(1000).nullable().default(null) }).superRefine((v, ctx) => { if (v.listType === "recommended" && !v.recommendationReason) ctx.addIssue({ code: "custom", path: ["recommendationReason"], message: "推薦頻道必須填寫理由" }); });
export const contentUpdateSchema = z.object({ title: z.string().trim().min(1).max(500).optional(), channelTitle: z.string().trim().max(300).nullable().optional(), shortSummary: z.string().trim().max(3000).optional(), difficulty: z.enum(["beginner", "normal"]).optional(), tags: z.array(z.string().trim().min(1).max(100)).max(30).optional(), status: z.enum(["discovered", "published", "hidden"]).optional(), hiddenReason: z.string().trim().max(1000).nullable().optional(), isPinned: z.boolean().optional(), topicId: z.string().uuid().nullable().optional() }).refine(v => Object.keys(v).length > 0, "至少需要一個欄位");
export const manualYoutubeSchema = z.object({ url: z.string().url(), topicId: z.string().uuid().nullable().default(null), publishImmediately: z.boolean().default(false), title: z.string().trim().min(1).max(500).default("手動新增的 YouTube 影片") }).transform(v => { const parsed = new URL(v.url); const id = parsed.hostname === "youtu.be" ? parsed.pathname.slice(1) : parsed.searchParams.get("v"); if (!id || !/^[\w-]{6,20}$/.test(id)) throw new Error("無效的 YouTube URL"); return { ...v, sourceContentId: id, sourceUrl: `https://www.youtube.com/watch?v=${id}` }; });
