"use client";

import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import type { ContentItem, SearchSettings } from "@/server/admin/types";

type Feedback = { kind: "success" | "error"; message: string } | null;

async function mutate(url: string, method: string, body?: unknown) {
  const response = await fetch(url, { method, headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined });
  const payload = await response.json().catch(() => null) as { error?: { message?: string } | string } | null;
  if (!response.ok) throw new Error(typeof payload?.error === "string" ? payload.error : payload?.error?.message ?? `操作失敗 (${response.status})`);
  return payload;
}

function Status({ feedback }: { feedback: Feedback }) { return feedback ? <p className={`admin-feedback admin-feedback--${feedback.kind}`} role={feedback.kind === "error" ? "alert" : "status"}>{feedback.message}</p> : null; }

export function TopicCreateForm({ canWrite }: { canWrite: boolean }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [feedback, setFeedback] = useState<Feedback>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); setPending(true); setFeedback(null); try { await mutate("/api/admin/topics", "POST", { slug: form.get("slug"), nameZhHant: form.get("nameZhHant"), keywords: form.get("keyword") ? [{ keyword: form.get("keyword"), keywordType: form.get("keywordType"), weight: 1, isActive: true }] : [] }); formElement.reset(); setFeedback({ kind: "success", message: "主題已新增" }); router.refresh(); } catch (error) { setFeedback({ kind: "error", message: error instanceof Error ? error.message : "新增失敗" }); } finally { setPending(false); } }
  if (!canWrite) return null;
  return <form className="admin-panel admin-form" onSubmit={submit}><h2 className="admin-form-title">新增主題</h2><label>名稱<input name="nameZhHant" required maxLength={200}/></label><label>Slug<input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*"/></label><label>第一個關鍵字<input name="keyword" maxLength={200}/></label><label>關鍵字類型<select name="keywordType" defaultValue="tw_term"><option value="tw_term">台灣用語</option><option value="cn_term">中國用語</option><option value="english">英文</option><option value="positive">正向</option><option value="negative">排除</option><option value="synonym">同義詞</option></select></label><div><button className="admin-button" disabled={pending}>{pending ? "新增中…" : "新增主題"}</button><Status feedback={feedback}/></div></form>;
}

export function DisableTopicButton({ id, canWrite }: { id: string; canWrite: boolean }) { const router=useRouter(); const [pending,setPending]=useState(false); const [feedback,setFeedback]=useState<Feedback>(null); if(!canWrite)return null; async function disable(){if(!confirm("確定停用此主題？既有資料會保留。"))return;setPending(true);try{await mutate(`/api/admin/topics/${id}`,"DELETE");setFeedback({kind:"success",message:"已停用"});router.refresh();}catch(e){setFeedback({kind:"error",message:e instanceof Error?e.message:"停用失敗"});}finally{setPending(false);}} return <div><button className="admin-button admin-button--secondary" type="button" disabled={pending} onClick={disable}>{pending?"停用中…":"停用"}</button><Status feedback={feedback}/></div>; }

export function SettingsEditor({ settings, canWrite }: { settings: SearchSettings[]; canWrite: boolean }) { const router=useRouter(); const [pending,setPending]=useState<string|null>(null); const [feedback,setFeedback]=useState<Feedback>(null); if(!canWrite)return null; async function submit(event:FormEvent<HTMLFormElement>, current:SearchSettings){event.preventDefault();const form=new FormData(event.currentTarget);setPending(current.topicId);setFeedback(null);try{await mutate("/api/admin/settings","PATCH",{...current,freshnessDays:Number(form.get("freshnessDays")),candidateLimit:Number(form.get("candidateLimit")),topN:Number(form.get("topN")),minDurationSeconds:Number(form.get("minDurationSeconds")),maxDurationSeconds:Number(form.get("maxDurationSeconds")),minEngagementScore:Number(form.get("minEngagementScore")),autoPublish:form.get("autoPublish")==="on"});setFeedback({kind:"success",message:"設定已儲存"});router.refresh();}catch(e){setFeedback({kind:"error",message:e instanceof Error?e.message:"儲存失敗"});}finally{setPending(null);}} return <div>{settings.map(item=><form className="admin-panel admin-form" key={item.topicId} onSubmit={e=>submit(e,item)}><h2 className="admin-form-title">編輯 {item.topicId}</h2><label>Freshness 天數<input name="freshnessDays" type="number" min="1" max="3650" defaultValue={item.freshnessDays} required/></label><label>候選上限<input name="candidateLimit" type="number" min="1" max="500" defaultValue={item.candidateLimit} required/></label><label>Top N<input name="topN" type="number" min="1" max="100" defaultValue={item.topN} required/></label><label>最短秒數<input name="minDurationSeconds" type="number" min="0" max="86400" defaultValue={item.minDurationSeconds} required/></label><label>最長秒數<input name="maxDurationSeconds" type="number" min="1" max="86400" defaultValue={item.maxDurationSeconds} required/></label><label>最低互動率<input name="minEngagementScore" type="number" min="0" max="1" step="0.001" defaultValue={item.minEngagementScore} required/></label><label className="admin-check"><input name="autoPublish" type="checkbox" defaultChecked={item.autoPublish}/> 自動發布</label><div><button className="admin-button" disabled={pending===item.topicId}>{pending===item.topicId?"儲存中…":"儲存設定"}</button></div></form>)}<Status feedback={feedback}/></div>; }

export function ChannelCreateForm({ canWrite }: { canWrite:boolean }) { const router=useRouter();const[pending,setPending]=useState(false);const[feedback,setFeedback]=useState<Feedback>(null);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const formElement=e.currentTarget;const f=new FormData(formElement);const listType=String(f.get("listType"));setPending(true);setFeedback(null);try{await mutate(`/api/admin/channels/${listType==="recommended"?"recommended":"blacklist"}`,"POST",{sourceChannelId:f.get("sourceChannelId"),handle:f.get("handle")||null,title:f.get("title"),trustWeight:Number(f.get("trustWeight")),recommendationReason:listType==="recommended"?f.get("recommendationReason")||null:null});formElement.reset();setFeedback({kind:"success",message:"頻道規則已新增"});router.refresh();}catch(error){setFeedback({kind:"error",message:error instanceof Error?error.message:"新增失敗"});}finally{setPending(false);}} if(!canWrite)return null;return <form className="admin-panel admin-form" onSubmit={submit}><h2 className="admin-form-title">新增頻道規則</h2><label>類型<select name="listType"><option value="recommended">推薦</option><option value="blacklisted">黑名單</option></select></label><label>Channel ID<input name="sourceChannelId" required/></label><label>名稱<input name="title" required/></label><label>Handle<input name="handle" placeholder="@channel"/></label><label>權重<input name="trustWeight" type="number" min="-10" max="10" step="0.1" defaultValue="0" required/></label><label>推薦理由<textarea name="recommendationReason" maxLength={1000}/></label><div><button className="admin-button" disabled={pending}>{pending?"新增中…":"新增規則"}</button><Status feedback={feedback}/></div></form>; }

export function ManualContentForm({ canWrite }: { canWrite:boolean }) { const router=useRouter();const[pending,setPending]=useState(false);const[feedback,setFeedback]=useState<Feedback>(null);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const formElement=e.currentTarget;const f=new FormData(formElement);setPending(true);setFeedback(null);try{await mutate("/api/admin/content/manual-youtube","POST",{url:f.get("url"),title:f.get("title"),topicId:f.get("topicId")||null,publishImmediately:f.get("publishImmediately")==="on"});formElement.reset();setFeedback({kind:"success",message:"YouTube 內容已新增"});router.refresh();}catch(error){setFeedback({kind:"error",message:error instanceof Error?error.message:"新增失敗"});}finally{setPending(false);}}if(!canWrite)return null;return <form className="admin-panel admin-form" onSubmit={submit}><h2 className="admin-form-title">手動新增 YouTube</h2><label>影片網址<input name="url" type="url" required placeholder="https://www.youtube.com/watch?v=…"/></label><label>標題<input name="title" required/></label><label>Topic UUID（選填）<input name="topicId"/></label><label className="admin-check"><input name="publishImmediately" type="checkbox"/> 立即發布</label><div><button className="admin-button" disabled={pending}>{pending?"新增中…":"新增內容"}</button><Status feedback={feedback}/></div></form>; }

export function ContentActions({ item, canWrite }: { item:ContentItem; canWrite:boolean }) { const router=useRouter();const[pending,setPending]=useState(false);const[feedback,setFeedback]=useState<Feedback>(null);if(!canWrite)return null;async function action(method:string,body?:unknown){setPending(true);setFeedback(null);try{await mutate(`/api/admin/content/${item.id}`,method,body);setFeedback({kind:"success",message:"內容已更新"});router.refresh();}catch(e){setFeedback({kind:"error",message:e instanceof Error?e.message:"更新失敗"});}finally{setPending(false);}}return <div className="admin-actions"><button type="button" disabled={pending} onClick={()=>action("PATCH",{status:item.status==="published"?"hidden":"published",hiddenReason:item.status==="published"?"管理者隱藏":null})}>{item.status==="published"?"隱藏":"發布"}</button><button type="button" disabled={pending} onClick={()=>confirm("確定刪除此內容？資料會以 soft delete 保留。")&&action("DELETE")}>刪除</button><Status feedback={feedback}/></div>; }

export function TriggerRunButton({ canWrite }: { canWrite:boolean }) { const router=useRouter();const[pending,setPending]=useState(false);const[feedback,setFeedback]=useState<Feedback>(null);if(!canWrite)return null;async function trigger(){setPending(true);setFeedback(null);try{await mutate("/api/admin/runs/trigger","POST");setFeedback({kind:"success",message:"Run 已排入佇列"});router.refresh();}catch(e){setFeedback({kind:"error",message:e instanceof Error?e.message:"觸發失敗"});}finally{setPending(false);}}return <div><button className="admin-button" type="button" disabled={pending} onClick={trigger}>{pending?"觸發中…":"手動觸發 Run"}</button><Status feedback={feedback}/></div>; }
