import type { ContentDetail } from "./types";

const quiz = (seed: number, subject: string): NonNullable<ContentDetail["quiz"]> => ({
  id: `00000000-0000-4000-8000-${String(seed).padStart(12, "0")}`,
  questions: [
    {
      id: `10000000-0000-4000-8000-${String(seed * 10 + 1).padStart(12, "0")}`,
      questionType: "comprehension",
      questionText: `學習 ${subject} 時，第一步最應該做什麼？`,
      options: { A: "先釐清問題與目標", B: "直接上線", C: "忽略資料品質", D: "只比較模型大小" },
      correctOptionKey: "A",
      explanation: "先定義問題與可驗證的目標，後續的工具與實作選擇才有依據。",
      evidenceText: "先釐清需求，再建立可以驗證的最小流程。",
      sortOrder: 0,
    },
    {
      id: `10000000-0000-4000-8000-${String(seed * 10 + 2).padStart(12, "0")}`,
      questionType: "application",
      questionText: "要降低實作風險，哪一種方式最好？",
      options: { A: "一次加入全部功能", B: "建立小型測試案例", C: "跳過評估", D: "只看展示結果" },
      correctOptionKey: "B",
      explanation: "小型測試案例能快速驗證假設，也能提供後續迭代的比較基準。",
      evidenceText: "以小型案例建立基準，逐步加入功能並持續評估。",
      sortOrder: 1,
    },
    {
      id: `10000000-0000-4000-8000-${String(seed * 10 + 3).padStart(12, "0")}`,
      questionType: "concept",
      questionText: "影片最強調的核心原則是什麼？",
      options: { A: "工具愈多愈好", B: "速度永遠優先", C: "可驗證且可重複", D: "不需要紀錄" },
      correctOptionKey: "C",
      explanation: "可驗證、可重複的流程能讓團隊辨識改善是否真的有效。",
      evidenceText: "每一步都要留下可重複的輸入與可驗證的輸出。",
      sortOrder: 2,
    },
  ],
});

export const demoContent: ContentDetail[] = [
  {
    id: "20000000-0000-4000-8000-000000000001", sourceType: "youtube", sourceUrl: "https://www.youtube.com/watch?v=demo-rag", thumbnailUrl: null,
    title: "從零打造 RAG：讓 AI 讀懂你的私有知識庫", channelTitle: "AI 工程筆記", publishedAt: "2026-07-02T02:00:00.000Z",
    viewCount: 38000, likeCount: 2800, commentCount: 390, engagementScore: 0.084, freshEngagementScore: 0.91, radarScore: 0.94,
    difficulty: "beginner", contentType: "tutorial", language: "zh-Hant", isRecommendedChannel: true,
    tags: ["RAG", "向量資料庫"], suitableFor: "想把生成式 AI 導入實際專案的開發者",
    shortSummary: "從文件切分、向量檢索到回答生成，逐步拆解一套可落地的 RAG 流程。",
    learningObjectives: ["理解 RAG 的資料流", "建立基本檢索管線", "辨識常見品質問題"], quizCount: 3,
    description: "以可執行範例介紹檢索增強生成的完整生命週期。", durationSeconds: 1694,
    fullSummary: "影片先說明語言模型知識時效與私有資料的限制，再建立文件切分、向量化、檢索與回答生成管線。後半段以命中率和答案忠實度檢查品質，並示範如何從失敗案例調整 chunk 與查詢策略。",
    transcriptSummary: "涵蓋 chunking、embedding、vector search、reranking、grounded generation 與評估。",
    limitationsOrCautions: "示範資料量較小；正式環境仍需評估權限、個資與索引更新策略。", topicNames: ["人工智慧", "RAG 入門"], quiz: quiz(1, "RAG"),
  },
  {
    id: "20000000-0000-4000-8000-000000000002", sourceType: "youtube", sourceUrl: "https://www.youtube.com/watch?v=demo-agent", thumbnailUrl: null,
    title: "AI Agent 工作流實戰：從工具呼叫到任務規劃", channelTitle: "生成式 AI 實驗室", publishedAt: "2026-06-30T02:00:00.000Z",
    viewCount: 21000, likeCount: 1300, commentCount: 360, engagementScore: 0.079, freshEngagementScore: 0.82, radarScore: 0.88,
    difficulty: "normal", contentType: "tutorial", language: "zh-Hant", isRecommendedChannel: true,
    tags: ["AI Agent", "Workflow"], suitableFor: "已熟悉提示工程，想建立自動化流程的人",
    shortSummary: "用完整案例說明 Agent 如何選擇工具、保留狀態與處理失敗。",
    learningObjectives: ["設計工具介面", "拆解任務步驟", "處理執行失敗"], quizCount: 3,
    description: "由單一步驟工具呼叫逐步擴充成可觀測的 Agent 工作流。", durationSeconds: 2466,
    fullSummary: "影片比較自主 Agent 與明確工作流的使用時機，逐步實作工具 schema、狀態保存、錯誤重試與人工確認。案例特別強調高風險操作需要權限邊界與稽核紀錄。",
    transcriptSummary: "涵蓋 tool calling、planning、state、retry、human-in-the-loop 與 observability。",
    limitationsOrCautions: "自主規劃會增加延遲與不可預期性；高風險動作必須加入確認。", topicNames: ["人工智慧", "AI Agent 入門"], quiz: quiz(2, "AI Agent"),
  },
  {
    id: "20000000-0000-4000-8000-000000000003", sourceType: "youtube", sourceUrl: "https://www.youtube.com/watch?v=demo-prompt", thumbnailUrl: null,
    title: "提示工程入門：寫出穩定、可重複的好提示", channelTitle: "數位學習所", publishedAt: "2026-06-28T02:00:00.000Z",
    viewCount: 64000, likeCount: 4100, commentCount: 510, engagementScore: 0.072, freshEngagementScore: 0.78, radarScore: 0.86,
    difficulty: "beginner", contentType: "tutorial", language: "zh-Hant", isRecommendedChannel: false,
    tags: ["Prompt", "入門"], suitableFor: "剛開始使用生成式 AI 的學習者",
    shortSummary: "以前後對照示範背景、限制與輸出格式如何影響模型結果。",
    learningObjectives: ["掌握提示四要素", "改善模糊指令", "建立可重用模板"], quizCount: 3,
    description: "從常見失敗提示出發，建立簡單且可重複的提示設計流程。", durationSeconds: 1112,
    fullSummary: "影片用具體案例拆解任務、背景、限制和輸出格式四個部分，說明如何用範例降低歧義。最後介紹以固定測試集比較提示版本，而不是只憑單次結果判斷品質。",
    transcriptSummary: "涵蓋 prompt anatomy、few-shot examples、constraints、structured output 與 evaluation。",
    limitationsOrCautions: "提示無法取代正確資料與系統層驗證；重要輸出仍需檢查。", topicNames: ["人工智慧", "Prompt Engineering"], quiz: quiz(3, "提示工程"),
  },
  {
    id: "20000000-0000-4000-8000-000000000004", sourceType: "youtube", sourceUrl: "https://www.youtube.com/watch?v=demo-local", thumbnailUrl: null,
    title: "本機大型語言模型：硬體選擇、量化與部署指南", channelTitle: "開源模型觀察站", publishedAt: "2026-06-26T02:00:00.000Z",
    viewCount: 17000, likeCount: 960, commentCount: 196, engagementScore: 0.068, freshEngagementScore: 0.66, radarScore: 0.79,
    difficulty: "normal", contentType: "tutorial", language: "zh-Hant", isRecommendedChannel: false,
    tags: ["LLM", "本機部署"], suitableFor: "重視資料隱私，準備在本機執行模型的技術團隊",
    shortSummary: "比較模型尺寸、記憶體需求與量化方法，說明部署時的效能取捨。",
    learningObjectives: ["估算硬體需求", "選擇量化格式", "規劃部署方式"], quizCount: 3,
    description: "以實測資料比較不同模型與量化設定的記憶體和輸出速度。", durationSeconds: 2148,
    fullSummary: "影片先建立參數量、精度與記憶體的估算方式，再比較 CPU、GPU 和統一記憶體平台。部署章節介紹量化格式、context 長度、批次處理與 API 服務的取捨。",
    transcriptSummary: "涵蓋 VRAM estimation、quantization、context window、throughput、latency 與 serving。",
    limitationsOrCautions: "硬體與框架更新快速，實際效能仍需用目標模型和工作負載測量。", topicNames: ["人工智慧", "LLM 入門"], quiz: quiz(4, "本機模型"),
  },
];
